<?php

namespace Plugin\CMBlog\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\CMBlog\Entity\BlogStatus;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * BlogStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogStatusRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, BlogStatus::class);
    }
}
